version: '2'
services: 
  web:
    build: .
    ports: 
      - "80:5000"
    volumes: 
      - /tmp/pets-api:/tmp/pets-api 
    links: 
      - db:mongodb
    container_name: petsapi_web_1
    depends_on: 
      