#
# Pets-Api Dockerfile
#

FROM python:3.4.5-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    make \
    gcc \
    python3-dev \
    mongodb

RUN mkdir /tmp/pets-api

WORKDIR /the/workdir/path